# Generated by Django 5.2.11 on 2026-02-11 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='education',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='links',
            field=models.TextField(blank=True, help_text='Comma-separated URLs'),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='work_experience',
            field=models.TextField(blank=True),
        ),
    ]
