# Generated by Django 5.0 on 2026-02-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_jobseekerprofile_education_jobseekerprofile_links_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='location',
            field=models.CharField(blank=True, help_text='City, State', max_length=255),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='projects',
            field=models.TextField(blank=True, help_text='List of projects for search'),
        ),
    ]
