# Generated by Django 5.2.11 on 2026-02-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_jobseekerprofile_education_jobseekerprofile_links_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobseekerprofile",
            name="show_education",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="show_headline",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="show_links",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="show_skills",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="show_work_experience",
            field=models.BooleanField(default=True),
        ),
    ]
