# Generated by Django 5.2.11 on 2026-02-13 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_jobseekerprofile_location_jobseekerprofile_projects'),
        ('users', '0003_jobseekerprofile_show_education_and_more'),
    ]

    operations = [
    ]
