# Generated by Django 5.0 on 2026-02-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_jobseekerprofile_show_education_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recruiterprofile",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="e.g. Technical Recruiter, Hiring Manager",
                max_length=255,
            ),
        ),
    ]
