# Generated by Django 5.0 on 2026-02-15 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_merge_20260213_0539"),
        ("users", "0004_recruiterprofile_title"),
    ]

    operations = []
