# Generated by Django 5.2.11 on 2026-02-15 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_merge_20260215_1958"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobseekerprofile",
            name="show_projects",
            field=models.BooleanField(default=True),
        ),
    ]
