# Generated by Django 5.2.11 on 2026-02-15 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_jobseekerprofile_show_projects"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobseekerprofile",
            name="show_location",
            field=models.BooleanField(default=True),
        ),
    ]
