# Generated by Django 5.2.11 on 2026-02-16 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_jobseekerprofile_show_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='preferred_commute_radius_miles',
            field=models.PositiveIntegerField(default=10, help_text='Preferred commute radius in miles'),
        ),
    ]
