# Generated by Django 5.2.11 on 2026-02-16 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_jobseekerprofile_preferred_commute_radius_miles'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='state',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='street_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='zip_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
