# Generated by Django 5.2.11 on 2026-02-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_jobseekerprofile_city_jobseekerprofile_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobseekerprofile",
            name="show_commute_radius",
            field=models.BooleanField(default=True),
        ),
    ]
