# Generated by Django 5.2.12 on 2026-03-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('SPAM', 'Spam / Rejected')], default='APPROVED', help_text='Moderation status of the job posting', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('street_address', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=2)),
                ('zip_code', models.CharField(blank=True, default='', max_length=10)),
                ('salary_range', models.CharField(max_length=100)),
                ('min_salary', models.IntegerField(blank=True, null=True)),
                ('max_salary', models.IntegerField(blank=True, null=True)),
                ('skills', models.CharField(blank=True, default='', help_text='Comma-separated skills (e.g. Python, Java)', max_length=255)),
                ('is_remote', models.BooleanField(default=False)),
                ('visa_sponsorship', models.BooleanField(default=False)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
