# Generated by Django 5.2.11 on 2026-02-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="skills",
            field=models.TextField(
                blank=True, help_text="Comma-separated required skills"
            ),
        ),
    ]
