# Generated by Django 5.0 on 2026-02-12 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_jobposting_max_salary_jobposting_min_salary_and_more"),
        ("jobs", "0002_jobposting_skills"),
    ]

    operations = []
