# Generated by Django 5.2.11 on 2026-02-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobposting_max_salary_jobposting_min_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='skills',
            field=models.TextField(blank=True, help_text='Comma-separated required skills'),
        ),
    ]
