# Generated by Django 5.2.11 on 2026-02-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_jobposting_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='skills',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
