# Generated by Django 5.0 on 2026-02-15 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_merge_20260212_2056"),
        ("jobs", "0005_alter_jobposting_skills"),
    ]

    operations = []
