# Generated by Django 5.2.11 on 2026-02-15 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0006_merge_20260215_1958"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobposting",
            name="skills",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Comma-separated skills (e.g. Python, Java)",
                max_length=255,
            ),
        ),
    ]
