# Generated by Django 5.2.12 on 2026-03-07 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_jobposting_city_jobposting_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('SPAM', 'Spam / Rejected')], default='PENDING', help_text='Moderation status of the job posting', max_length=20),
        ),
    ]
