# Generated by Django 5.2.12 on 2026-03-07 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_jobposting_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('SPAM', 'Spam / Rejected')], default='APPROVED', help_text='Moderation status of the job posting', max_length=20),
        ),
    ]
